#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION "2019.4.17f1"
#define UNITY_VERSION_DIGITS "2019.4.17"
#define UNITY_VERSION_SUFFIX "f1"
#define UNITY_VERSION_VER 2019
#define UNITY_VERSION_MAJ 4
#define UNITY_VERSION_MIN 17
#define UNITY_IS_BETA 0
